#当前 Eureka Server 服务端口号
server:
  port: 8761


#配置 Eureka Server 注册中心
eureka:
  client:
    register-with-eureka: false   #是否将当前的Eureka Server服务作为客户端注册（注册自己）
    fetch-registry: false         #是否要同步其他的Eureka Server服务的数据
    service-url:                  #访问注册中心的地址
      defaultZone: http://localhost:8761/eureka/

