#服务端口号
server:
  port: 8030


# 当前服务 注册在 Eureka Server名字
spring:
  application:
    name: gateway   #网关 的名字


#配置 Eureka Server 注册中心
eureka:
  client:
    service-url:              #注册中心的地址
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true   #是否将当前服务的 ip注册到 Eureka Server


#zuul 对 provider 映射 配置
zuul:
  routes:
    provider: /p/**   #给 服务提供者设置映射    【获取provider，provider 是服务提供者的注册的名字，p 是provider的别名【只要请求里面是p/ 访问的是就provider】】


