#Spring Cloud Config 远程配置

#端口号
server:
  port: 8071

#配置Eureka Server注册中心 【注册中心的地址】
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#当前服务注册在Eureka Server名字
spring:
  application:
    name: configclient
