#【Config Server】配置

#服务端口号
server:
  port: 8762


spring:
  application:
    name: configserverBenDi  # 服务 名字
  #配置文件的获取方式 (native 从本地)
  profiles:
    active: native
  #本地配置文件存放的路径
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared   #resources 路径下创建shared文件夹，并在此路径下创建 configclient-dev.yml





