#【Hystrix】配置

#服务端口号
server:
  port: 8060

# 当前服务注册在 Eureka Server名字
spring:
  application:
    name: hystrix

#配置Eureka Server注册中心【#注册中心的地址】
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true   #是否将当前服务的 ip地址 注册到 Eureka Server

#配置 feign 熔断器
feign:
  hystrix:
    enabled: true    #是否开启熔断器

#配置数据监控 (#通过 hystrix.stream 节点获取监控的请求数据)
management:
  endpoints:
    web:
      exposure:
        include: 'hystrix.stream'




